name: Build Android and iOS
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn install
      - name: Run tests
        run: |
          yarn test
  build-android:
      needs: install-and-test
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v2
        - name: Install npm dependencies
          run: |
            npm install
        - name: Build Android Release
          run: |
            cd android && ./gradlew assembleDebug assembleAndroidTest
        - name: Upload Artifact
          uses: actions/upload-artifact@v1
          with:
            name: app-debug-androidTest.apk
            path: android/app/build/outputs/apk/androidTest/debug/
          
          
          
